#!/usr/bin/python3
#
#   Ewia - A tool to calculate astrophysical object positions.
#   Copyright (C) 2017-2017 Johannes Bauer
#
#   This file is part of Ewia.
#
#    Ewia is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; this program is ONLY licensed under
#    version 2 of the License, later versions are explicitly excluded.
#
#    Ewia is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Ewia; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   Johannes Bauer <JohannesBauer@gmx.de>
import sys

from FriendlyArgumentParser import FriendlyArgumentParser
from ObjectCatalog import ObjectCatalog

parser = FriendlyArgumentParser()
parser.add_argument("-c", "--user-catalog", metavar = "filename", type = str, action = "append", default = [ ], help = "Specifies user catalogs to read after system catalogs have been read.")
parser.add_argument("--no-system-catalog", action = "store_true", help = "Do not read system catalogs (by default, ~/.config/ewia/catalog.json and ./.catalog.json are tried)")
args = parser.parse_args(sys.argv[1:])

catalog = ObjectCatalog()
if not args.no_system_catalog:
	for system_catalog_filename in [ "~/.config/ewia/catalog.json", ".catalog.json" ]:
		catalog.append_from_file(system_catalog_filename, fail_on_error = False)
for user_catalog_filename in args.user_catalog:
	catalog.append_from_file(system_catalog_filename, fail_on_error = True)


